#ifndef SCREEN_SPACE_REFLECTION_VARIABLES_INCLUDED
#define SCREEN_SPACE_REFLECTION_VARIABLES_INCLUDED

// Should match ScreenSpaceReflectionTracePass.ScreenSpaceReflectionVariables
CBUFFER_START (ShaderVariablesScreenSpaceReflection)
float4x4 _SSR_ProjectionMatrix;

float _SSRIntensity;

float _SsrRoughnessFadeEnd;
float _SsrRoughnessFadeRcpLength;

float _SsrRoughnessFadeEndTimesRcpLength;
float _SsrEdgeFadeRcpLength;
int _SsrDepthPyramidMaxMip;

CBUFFER_END

#endif
